/* not authorized for copy  or distribute or reuse */
package fuzzysemafor;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/* Tia Shami */
public class SemaFrame extends javax.swing.JFrame {

    public  FileWriter fw;
  
 public int ir1,ir2,ir3,is1,is2,is3,il1,il2,il3,is4,ir4,il4;//density for all road
 int SH,SP,LH,LP; // competitive sums
int winner, secwin,temp ;
String lastwin =" ";//save last winner 
int greentime ,countwin=0;// count how many times the same semaphore win
String winname,secname,tname;
public float green = 0;
    public      int greent;
    public String gr;
     public   Counter cc= new Counter();
 public   Timer t = new Timer(1000,cc );
 public int max(int a, int b){
 if(a>=b)return a;
 else return b;
 }
    public SemaFrame() {
        
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  =================timer clas start=========
   
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        s1 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        s4 = new javax.swing.JTextField();
        l4 = new javax.swing.JTextField();
        l2 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        l3 = new javax.swing.JTextField();
        lab2 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        sep1 = new javax.swing.JLabel();
        sep2 = new javax.swing.JLabel();
        sep3 = new javax.swing.JLabel();
        sep4 = new javax.swing.JLabel();
        sep5 = new javax.swing.JLabel();
        sep6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        info3 = new javax.swing.JTextField();
        info2 = new javax.swing.JTextField();
        info1 = new javax.swing.JTextField();
        info4 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        l4.setToolTipText("");

        lab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/area.png"))); // NOI18N

        lab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/area.png"))); // NOI18N

        lab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/area.png"))); // NOI18N

        lab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/area.png"))); // NOI18N

        sep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        sep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        sep3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        sep4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        sep5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        sep6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/separator.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel4.setText("jLabel1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/sep2.png"))); // NOI18N
        jLabel6.setText("jLabel1");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/car.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/car.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/car.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzysemafor/car.jpg"))); // NOI18N

        info3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info3ActionPerformed(evt);
            }
        });

        info2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info2ActionPerformed(evt);
            }
        });

        info1.setColumns(25);
        info1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        info1.setToolTipText("");
        info1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info1.setCaretColor(new java.awt.Color(255, 255, 255));
        info1.setMinimumSize(new java.awt.Dimension(25, 15));
        info1.setSelectedTextColor(new java.awt.Color(204, 0, 153));
        info1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info1ActionPerformed(evt);
            }
        });

        info4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info4ActionPerformed(evt);
            }
        });

        menu.setText("choose case");

        jMenuItem2.setText("case1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem2);

        jMenuItem3.setText("case2");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu.add(jMenuItem3);

        jMenuItem4.setText("herurcical (Fuzzy future work)");
        menu.add(jMenuItem4);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sep5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(sep6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(l2)
                                        .addComponent(s2)
                                        .addComponent(r2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sep4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)))
                            .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addComponent(info3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(info1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(593, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(496, Short.MAX_VALUE)
                    .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel10)
                    .addContainerGap(667, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(353, 353, 353)
                    .addComponent(info4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sep1)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)))
                        .addGap(17, 17, 17)
                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sep3)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(info2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel6)))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(sep4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(info1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(sep5)
                                .addGap(4, 4, 4)
                                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(sep6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel8)
                                        .addGap(35, 35, 35)
                                        .addComponent(info3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(36, 36, 36))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(595, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(264, 264, 264)
                    .addComponent(jLabel10)
                    .addContainerGap(505, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(info4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(666, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//generate random density  for case 1
    public  void rand1 (){
   ir1 = 3 + (int) (Math.random() * 8);
        is1 = 30 + (int) (Math.random() * 50);
        il1 = 10 + (int) (Math.random() * 30);
        ir2 = 2 + (int) (Math.random() * 5);
        is2 = 10 + (int) (Math.random() * 15);
        il2 = 10 + (int) (Math.random() * 20);
        ir3 = 1 + (int) (Math.random() * 6);
        is3 = 25 + (int) (Math.random() * 35);
        il3 = 20 + (int) (Math.random() * 33);
        ir4 = 1 + (int) (Math.random() * 6);
        is4 = 20 + (int) (Math.random() * 40);
        il4 = 20 + (int) (Math.random() * 40);
}/*  intialize the info  text    calculate  winner  set colors */
    
    public void initfuzwinset(){
    String inf1,inf2,inf3,inf4;
    
        inf1 = "R1=    " + Integer.toString(ir1) + "   S1=    " + Integer.toString(is1) + " L1=    " + Integer.toString(il1);
        inf2 = " R2=   " + Integer.toString(ir2) + "   S2=    " + Integer.toString(is2) + "     L2=   " + Integer.toString(il2);
        inf3 = " R3=   " + Integer.toString(ir3) + "   S3=    " + Integer.toString(is3) + "    L3=   " + Integer.toString(il3);
        inf4 = " R4=   " + Integer.toString(ir4) + "    S4=    " + Integer.toString(is4) + "    L4=   " + Integer.toString(il4);
       //display roads density
        info1.setText(inf1);
        info2.setText(inf2);
        info3.setText(inf3);
        info4.setText(inf4);
        // dtermine the winner
        SH=is1+is2;
        SP=is3+is4;
        LH=il1+il2;
        LP=il3+il4;
winner= max(max(SH,SP),max(LH,LP));
if(winner==SH){ winname="SH";  secwin=max(LH,max(SP,LP));}
if(winner==LH) {winname="LH"; secwin=max(SH,max(SP,LP));}
if(winner==SP){ winname="SP";secwin=max(LP,max(SH,LH));}
if(winner==LP){ winname="LP";secwin=max(SP,max(SH,LH));}
 if(secwin==SH) secname="SH" ;   
  if(secwin==SP) secname="SP" ; 
  if(secwin==LH) secname="LH" ; 
  if(secwin==LP) secname="LP" ; 
         //checking  if anyone win twice?
         if (lastwin.equalsIgnoreCase(winname)) countwin++;
         if (countwin>2){
       winner=secwin;
       winname=secname;
       secwin =(SH+LH+SP+LP)/4;
       secname="ER";
         }
         
             Fuzzyclass fsystem =new Fuzzyclass();
   green = fsystem.fuzzify2val((winner/2),( secwin/2));
    greent =(int)green;
    greentime=greent;
     
      
       try {

         //   fw = new FileWriter(new File("rezults.txt",true));
            fw = new FileWriter("rezults.txt", true);
             
            fw.write(inf1+inf2+inf3+inf4+ "    second winner is :   "  + secname+"    winner is :    "+winname+ "   green Time for wiiner:     "+Integer.toString(greent));

            fw.write(System.lineSeparator()); //new line

            fw.close();

        } catch (IOException ex) {
            ex.printStackTrace();

        }

      
      if(winname=="SH"){
     l1.setBackground(Color.red);
     r1.setBackground(Color.green);
     s1.setBackground(Color.green);
     l2.setBackground(Color.red);
     r2.setBackground(Color.green);
     s2.setBackground(Color.green);
     l3.setBackground(Color.red);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
     l4.setBackground(Color.red);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);
      
      }
      else if (winname=="SP")
      {l1.setBackground(Color.red);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.red);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.red);
     r3.setBackground(Color.green);
     s3.setBackground(Color.green);
     l4.setBackground(Color.red);
     r4.setBackground(Color.green);
     s4.setBackground(Color.green);}
      else if (winname=="LH")
      {l1.setBackground(Color.green);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.green);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.red);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
     l4.setBackground(Color.red);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);}
      else if (winname=="LP")
      {l1.setBackground(Color.red);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.red);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.green);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
    l4.setBackground(Color.green);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);}
      
     
      lastwin=winname;
      changedensity();
  
    }
        public void initfuzwinset2(){
    String inf1,inf2,inf3,inf4;
     try {

         //   fw = new FileWriter(new File("rezults.txt",true));
            fw = new FileWriter("rezults.txt", true);
             
            fw.write("case 2");

            fw.write(System.lineSeparator()); //new line
             fw.write("=======================");

            fw.write(System.lineSeparator()); //new line


            fw.close();

        } catch (IOException ex) {
            ex.printStackTrace();

        }
        inf1 = "R1=" + Integer.toString(ir1) + ",S1=" + Integer.toString(is1) + ",L1=" + Integer.toString(il1);
        inf2 = "R2=" + Integer.toString(ir2) + ",S2=" + Integer.toString(is2) + ",L2=" + Integer.toString(il2);
        inf3 = "R3=" + Integer.toString(ir3) + ",S3=" + Integer.toString(is3) + ",L3=" + Integer.toString(il3);
        inf4 = "R4=" + Integer.toString(ir4) + ",S4=" + Integer.toString(is4) + ",L4="  + Integer.toString(il4);
       //display roads density
        info1.setText(inf1);
        info2.setText(inf2);
        info3.setText(inf3);
        info4.setText(inf4);
        // dtermine the winner
        SH=is1+is2;
        SP=is3+is4;
        LH=il1+il2;
        LP=il3+il4;
winner= max(max(SH,SP),max(LH,LP));
if(winner==SH){ winname="SH";  secwin=max(LH,max(SP,LP));}
if(winner==LH) {winname="LH"; secwin=max(SH,max(SP,LP));}
if(winner==SP){ winname="SP";secwin=max(LP,max(SH,LH));}
if(winner==LP){ winname="LP";secwin=max(SP,max(SH,LH));}
 if(secwin==SH) secname="SH" ;   
  if(secwin==SP) secname="SP" ; 
  if(secwin==LH) secname="LH" ; 
  if(secwin==LP) secname="LP" ; 
         //checking  if anyone win twice?
         if (lastwin.equalsIgnoreCase(winname)) countwin++;
         if (countwin>2){
       winner=secwin;
       winname=secname;
       secwin =(SH+LH+SP+LP)/4;
       secname="ER";
         }
         
             Fuzzyclass fsystem =new Fuzzyclass();
   green = fsystem.fuzzify2val2((winner/2),( secwin/2));
    greent =(int)green;
    greentime=greent;
     
      
       try {

         //   fw = new FileWriter(new File("rezults.txt",true));
            fw = new FileWriter("rezults.txt", true);
             
            fw.write(inf1+inf2+inf3+inf4+ "    second winner is :   "  + secname+"    winner is :    "+winname+ "   green Time for wiiner:     "+Integer.toString(greent));

            fw.write(System.lineSeparator()); //new line

            fw.close();

        } catch (IOException ex) {
            ex.printStackTrace();

        }

      
      if(winname=="SH"){
     l1.setBackground(Color.red);
     r1.setBackground(Color.green);
     s1.setBackground(Color.green);
     l2.setBackground(Color.red);
     r2.setBackground(Color.green);
     s2.setBackground(Color.green);
     l3.setBackground(Color.red);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
     l4.setBackground(Color.red);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);
      
      }
      else if (winname=="SP")
      {l1.setBackground(Color.red);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.red);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.red);
     r3.setBackground(Color.green);
     s3.setBackground(Color.green);
     l4.setBackground(Color.red);
     r4.setBackground(Color.green);
     s4.setBackground(Color.green);}
      else if (winname=="LH")
      {l1.setBackground(Color.green);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.green);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.red);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
     l4.setBackground(Color.red);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);}
      else if (winname=="LP")
      {l1.setBackground(Color.red);
     r1.setBackground(Color.red);
     s1.setBackground(Color.red);
     l2.setBackground(Color.red);
     r2.setBackground(Color.red);
     s2.setBackground(Color.red);
     l3.setBackground(Color.green);
     r3.setBackground(Color.red);
     s3.setBackground(Color.red);
    l4.setBackground(Color.green);
     r4.setBackground(Color.red);
     s4.setBackground(Color.red);}
      
     
      lastwin=winname;
      changedensity();
  
    }
    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed
public void changedensity(){
ir1=(greentime/10) +ir1;
is1= (greentime/10)+is1;
il1=(greentime/10) +il1;
ir2=(greentime/10) +ir2;
is2= (greentime/10)+is2;
il2=(greentime/10) +il2;
ir3=(greentime/10) +ir3;
is3= (greentime/10)+is3;
il3=(greentime/10) +il3;
ir4=(greentime/10) +ir4;
is4= (greentime/10)+is4;
il4=greentime/10 +il4;
  if (lastwin.equals("SH")){
      is1= is1-(greentime/2);
      is2=is2-(greentime/2);
  ir1=ir1-(greentime/2);
  ir2=ir2- (greentime/2); }
   if (lastwin.equals("SP")){
      is3= is3-(greentime/2);
      is4=is4-(greentime/2);
   ir3=ir3-(greentime/2);
   ir4=ir4-(greentime/2);
   }
   if (lastwin.equals("LH")){
      il1= il1-(greentime/2);
      il2=il2-(greentime/2); }
   if (lastwin.equals("LP")){
      il3= il3-(greentime/2);
      il4=il4-(greentime/2); }
   if (ir1 <0) ir1 =0;
   if (is1 <0) is1 =0;
   if ( il1<0)il1 =0;
    if ( ir2<0) ir2=0;
   if (is2 <0)is2 =0;
   if ( il2<0)il2 =0;
    if ( ir3 <0)ir3 =0;
   if ( is3<0)is3 =0;
   if (il3 <0)il3 =0;
   if (ir4 <0) ir4 =0;
   if ( is4<0) is4=0;
   if (il4 <0) il4 =0;
   
}




    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      //generating the random numbers :)
     rand1();
      
   initfuzwinset();  
     t.start();
     
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed
class Counter implements ActionListener{
    public Counter(){}
public void actionPerformed(ActionEvent event)
         { 
            if (greent >= 0)
             gr =Integer.toString(greent);
          l1.setText(gr);
     r1.setText(gr);
     s1.setText(gr);
     l2.setText(gr);
     r2.setText(gr);
     s2.setText(gr);
     l3.setText(gr);
     r3.setText(gr);
     s3.setText(gr);
     l4.setText(gr);
     r4.setText(gr);
     s4.setText(gr);
          
            if (greent == 0){
                
                 
                initfuzwinset();
                t.start();
              }
            greent--;
         }}
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        rand1();
      
   initfuzwinset2();  
     t.start();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void info3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info3ActionPerformed

    private void info2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info2ActionPerformed

    private void info1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info1ActionPerformed

    private void info4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_info4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SemaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField info1;
    public javax.swing.JTextField info2;
    public javax.swing.JTextField info3;
    public javax.swing.JTextField info4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JTextField l1;
    public javax.swing.JTextField l2;
    public javax.swing.JTextField l3;
    public javax.swing.JTextField l4;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JMenu menu;
    public javax.swing.JTextField r1;
    public javax.swing.JTextField r2;
    public javax.swing.JTextField r3;
    public javax.swing.JTextField r4;
    public javax.swing.JTextField s1;
    public javax.swing.JTextField s2;
    public javax.swing.JTextField s3;
    public javax.swing.JTextField s4;
    private javax.swing.JLabel sep1;
    private javax.swing.JLabel sep2;
    private javax.swing.JLabel sep3;
    private javax.swing.JLabel sep4;
    private javax.swing.JLabel sep5;
    private javax.swing.JLabel sep6;
    // End of variables declaration//GEN-END:variables
}
